# Generated by Django 3.1.7 on 2023-03-12 13:07

from django.contrib.postgres.search import SearchVector
from django.db import migrations


def update_search_vector(apps, schema_editor):
    Wine = apps.get_model('catalog', 'Wine')
    Wine.objects.all().update(search_vector=(
        SearchVector('variety', weight='A') +
        SearchVector('winery', weight='A') +
        SearchVector('description', weight='B')
    ))


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '2'),
    ]

    operations = [
        migrations.RunPython(update_search_vector, elidable=True),
    ]
